export const NAVIGATION_PUSH = 'NAVIGATION_PUSH'
export const NAVIGATION_POP = 'NAVIGATION_POP'

export const TABBAR_SWITCH = 'TABBAR_SWITCH'

export const NAVIGATION_LOGIN_RESET = 'NAVIGATION_LOGIN_RESET'